
export const suggestions = [
   { article: "SP1401", brand: "Sangsin brake", price: 2021, day: 8 ,supplier:'ПарткКом 21',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1206, day: 7 ,supplier:'Микадо 3',supplierColor:'yellow',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2911, day: 9 ,supplier:'Иксора 1',supplierColor:'red',dayColor:'red',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1486, day: 5 ,supplier:'Автоевро 19',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1873, day: 2 ,supplier:'Берг 29',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2208, day: 8 ,supplier:'Роско 22',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2215, day: 8 ,supplier:'Армтек 33',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2137, day: 2 ,supplier:'ПарткКом 29',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2635, day: 9 ,supplier:'Микадо 46',supplierColor:'green',dayColor:'red',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 1560, day: 2 ,supplier:'Иксора 21',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1450, day: 10 ,supplier:'Автоевро 12',supplierColor:'green',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2648, day: 2 ,supplier:'Берг 42',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1714, day: 7 ,supplier:'Роско 8',supplierColor:'yellow',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2839, day: 10 ,supplier:'Армтек 7',supplierColor:'yellow',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2287, day: 9 ,supplier:'ПарткКом 1',supplierColor:'red',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2048, day: 2 ,supplier:'ПарткКом 18',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2368, day: 7 ,supplier:'Автоевро 45',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2032, day: 1 ,supplier:'Берг 44',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2628, day: 3 ,supplier:'Роско 6',supplierColor:'yellow',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2763, day: 7 ,supplier:'Микадо 42',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1567, day: 0 ,supplier:'Иксора 10',supplierColor:'yellow',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2399, day: 8 ,supplier:'Берг 11',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1260, day: 0 ,supplier:'Роско 47',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1813, day: 8 ,supplier:'Армтек 14',supplierColor:'green',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1782, day: 5 ,supplier:'ПарткКом 5',supplierColor:'yellow',dayColor:'yellow',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1650, day: 1 ,supplier:'Микадо 31',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2567, day: 2 ,supplier:'Иксора 37',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 2305, day: 0 ,supplier:'Автоевро 31',supplierColor:'green',dayColor:'green',remainder:'>10',remainderColor:'green'},
{ article: "SP1401", brand: "Sangsin brake", price: 1217, day: 10 ,supplier:'Берг 20',supplierColor:'green',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2112, day: 7 ,supplier:'Роско 28',supplierColor:'green',dayColor:'yellow',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 2082, day: 7 ,supplier:'Роско 29',supplierColor:'green',dayColor:'yellow',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 2390, day: 2 ,supplier:'Роско 30',supplierColor:'green',dayColor:'green',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 1472, day: 1 ,supplier:'Роско 31',supplierColor:'green',dayColor:'green',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 1571, day: 8 ,supplier:'Роско 32',supplierColor:'green',dayColor:'yellow',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 1151, day: 3 ,supplier:'Роско 33',supplierColor:'green',dayColor:'yellow',remainder:'02-10',remainderColor:'yellow'},
{ article: "SP1401", brand: "Sangsin brake", price: 2853, day: 3 ,supplier:'Роско 34',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2999, day: 5 ,supplier:'Роско 35',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2188, day: 2 ,supplier:'Роско 36',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1320, day: 0 ,supplier:'Роско 37',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2484, day: 1 ,supplier:'Роско 38',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2750, day: 7 ,supplier:'Роско 39',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1130, day: 9 ,supplier:'Роско 40',supplierColor:'green',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1238, day: 2 ,supplier:'Роско 41',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2431, day: 3 ,supplier:'Роско 42',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1937, day: 10 ,supplier:'Роско 43',supplierColor:'green',dayColor:'red',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2622, day: 2 ,supplier:'Роско 44',supplierColor:'green',dayColor:'green',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2119, day: 4 ,supplier:'Роско 45',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2348, day: 7 ,supplier:'Роско 46',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 2421, day: 4 ,supplier:'Роско 47',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
{ article: "SP1401", brand: "Sangsin brake", price: 1596, day: 6 ,supplier:'Роско 48',supplierColor:'green',dayColor:'yellow',remainder:'<2',remainderColor:'red'},
    ];


